services:
  postgres:
    image: postgres:16-alpine
    container_name: anime
    environment:
      POSTGRES_USER: animeuser
      POSTGRES_PASSWORD: zEgvuzyDcPlQhcOQIPnaIZfFSsAeoXYILr8/lUD6Oes=
      POSTGRES_DB: anime
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myanimelist-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U animelistuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: myanimelist-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - myanimelist-network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: MyAnimeList.Backend/Dockerfile
    container_name: myanimelist-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=anime;Username=animeuser;Password=zEgvuzyDcPlQhcOQIPnaIZfFSsAeoXYILr8/lUD6Oes=;"
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - myanimelist-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  myanimelist-network:
    driver: bridge
